const FMX=(()=>{const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const initials=n=>(n||'MX').split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase();const fmtDate=d=>new Intl.DateTimeFormat('es-MX',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d));const fmtTime=d=>new Intl.DateTimeFormat('es-MX',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(d));function logo(u,n,c='mini-logo'){return u?`<img class="${c}" src="${esc(u)}" alt="Escudo de ${esc(n)}" loading="lazy">`:`<span class="mini-fallback">${initials(n)}</span>`}function setDataState(live,updated){const manual=!!window.FMX_MANUAL?.enabled&&!live;const label=live?'Datos conectados':manual?(window.FMX_MANUAL.label||'Datos actualizados manualmente'):'Datos disponibles';document.querySelectorAll('[data-state]').forEach(el=>el.textContent=label);document.querySelectorAll('[data-dot]').forEach(el=>el.classList.toggle('live',live||manual));const t=$('lastUpdated'),when=updated||window.FMX_MANUAL?.updatedAt;if(t)t.textContent=when?`Actualizado ${new Date(when).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}`:'Actualización pendiente'}const m=$('menuBtn'),l=$('navLinks');if(m&&l){const close=()=>{l.classList.remove('open');m.setAttribute('aria-expanded','false');m.setAttribute('aria-label','Abrir menú')};m.addEventListener('click',()=>{const open=l.classList.toggle('open');m.setAttribute('aria-expanded',String(open));m.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});l.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}return{$,esc,initials,fmtDate,fmtTime,logo,setDataState}})();

// Unidad Popunder de Adsterra. Solo se carga en el dominio público para no
// generar impresiones accidentales durante desarrollo o vistas previas.
if(location.hostname==='futbolmx.vercel.app'&&!document.querySelector('script[data-fmx-popunder]')){
  const popunder=document.createElement('script');
  popunder.src='https://bleatbehind.com/de/19/da/de19daa6600352a4fdbe4c24a3e4b6f3.js';
  popunder.async=true;
  popunder.dataset.fmxPopunder='adsterra';
  document.head.appendChild(popunder);
}
