window.FMX_MANUAL = { enabled:true, updatedAt:'2026-09-15T09:00:00-06:00', label:'Resultados y tabla verificados al 15 de septiembre de 2026' };

window.FMX_DEMO = {
  standings: [
    {rank:1,team:{id:8,name:'Chivas',logo:''},points:17,goalsDiff:9,form:'WDWWW',all:{played:8,win:5,draw:2,lose:1,goals:{for:15,against:6}}},
    {rank:2,team:{id:5,name:'Toluca',logo:''},points:16,goalsDiff:11,form:'WDWWW',all:{played:7,win:5,draw:1,lose:1,goals:{for:17,against:6}}},
    {rank:3,team:{id:1,name:'América',logo:''},points:16,goalsDiff:9,form:'WWWWL',all:{played:7,win:5,draw:1,lose:1,goals:{for:15,against:6}}},
    {rank:4,team:{id:9,name:'Cruz Azul',logo:''},points:15,goalsDiff:2,form:'LLWWW',all:{played:8,win:5,draw:0,lose:3,goals:{for:16,against:14}}},
    {rank:5,team:{id:7,name:'Querétaro',logo:''},points:13,goalsDiff:3,form:'WDLWW',all:{played:7,win:4,draw:1,lose:2,goals:{for:10,against:7}}},
    {rank:6,team:{id:14,name:'León',logo:''},points:13,goalsDiff:2,form:'WWDLW',all:{played:8,win:4,draw:1,lose:3,goals:{for:11,against:9}}},
    {rank:7,team:{id:2,name:'Tijuana',logo:''},points:13,goalsDiff:2,form:'DWLWL',all:{played:7,win:4,draw:1,lose:2,goals:{for:10,against:8}}},
    {rank:8,team:{id:12,name:'Puebla',logo:''},points:13,goalsDiff:1,form:'DWWLW',all:{played:7,win:4,draw:1,lose:2,goals:{for:10,against:9}}},
    {rank:9,team:{id:4,name:'Atlas',logo:''},points:13,goalsDiff:-2,form:'WWLDL',all:{played:8,win:4,draw:1,lose:3,goals:{for:12,against:14}}},
    {rank:10,team:{id:13,name:'Pachuca',logo:''},points:11,goalsDiff:5,form:'LDDWW',all:{played:8,win:3,draw:2,lose:3,goals:{for:13,against:8}}},
    {rank:11,team:{id:6,name:'Pumas UNAM',logo:''},points:11,goalsDiff:-1,form:'DDLWL',all:{played:8,win:3,draw:2,lose:3,goals:{for:11,against:12}}},
    {rank:12,team:{id:3,name:'Monterrey',logo:''},points:10,goalsDiff:3,form:'WWLLD',all:{played:7,win:3,draw:1,lose:3,goals:{for:13,against:10}}},
    {rank:13,team:{id:10,name:'Necaxa',logo:''},points:8,goalsDiff:-4,form:'LDLDL',all:{played:8,win:2,draw:2,lose:4,goals:{for:9,against:13}}},
    {rank:14,team:{id:16,name:'Tigres UANL',logo:''},points:7,goalsDiff:-2,form:'LWDDD',all:{played:8,win:1,draw:4,lose:3,goals:{for:9,against:11}}},
    {rank:15,team:{id:11,name:'Atlante',logo:''},points:7,goalsDiff:-5,form:'DLDDL',all:{played:8,win:1,draw:4,lose:3,goals:{for:7,against:12}}},
    {rank:16,team:{id:15,name:'Atlético San Luis',logo:''},points:6,goalsDiff:-7,form:'LDWLL',all:{played:8,win:1,draw:3,lose:4,goals:{for:8,against:15}}},
    {rank:17,team:{id:17,name:'Santos Laguna',logo:''},points:4,goalsDiff:-7,form:'LLDLW',all:{played:8,win:1,draw:1,lose:6,goals:{for:6,against:13}}},
    {rank:18,team:{id:18,name:'FC Juárez',logo:''},points:0,goalsDiff:-19,form:'LLLLL',all:{played:8,win:0,draw:0,lose:8,goals:{for:4,against:23}}}
  ],
  fixtures: [
    {fixture:{id:2901,date:'2026-09-11T17:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio Victoria',city:'Aguascalientes'}},league:{round:'Jornada 8'},teams:{home:{id:109,name:'Necaxa',logo:''},away:{id:104,name:'Puebla',logo:''}},goals:{home:0,away:1}},
    {fixture:{id:2902,date:'2026-09-11T19:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio Ciudad de los Deportes',city:'Ciudad de México'}},league:{round:'Jornada 8'},teams:{home:{id:105,name:'Atlante',logo:''},away:{id:118,name:'Pachuca',logo:''}},goals:{home:0,away:3}},
    {fixture:{id:2903,date:'2026-09-11T20:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio Caliente',city:'Tijuana'}},league:{round:'Jornada 8'},teams:{home:{id:119,name:'Tijuana',logo:''},away:{id:120,name:'Querétaro',logo:''}},goals:{home:0,away:1}},
    {fixture:{id:2904,date:'2026-09-12T18:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio Nemesio Díez',city:'Toluca'}},league:{round:'Jornada 8'},teams:{home:{id:116,name:'Toluca',logo:''},away:{id:110,name:'Atlas',logo:''}},goals:{home:5,away:2}},
    {fixture:{id:2905,date:'2026-09-12T18:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio BBVA',city:'Guadalupe'}},league:{round:'Jornada 8'},teams:{home:{id:112,name:'Monterrey',logo:''},away:{id:107,name:'Tigres UANL',logo:''}},goals:{home:0,away:0}},
    {fixture:{id:2906,date:'2026-09-12T20:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio Olímpico Universitario',city:'Ciudad de México'}},league:{round:'Jornada 8'},teams:{home:{id:113,name:'Cruz Azul',logo:''},away:{id:114,name:'América',logo:''}},goals:{home:4,away:3}},
    {fixture:{id:2907,date:'2026-09-13T16:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio TSM Corona',city:'Torreón'}},league:{round:'Jornada 8'},teams:{home:{id:117,name:'Santos Laguna',logo:''},away:{id:106,name:'FC Juárez',logo:''}},goals:{home:2,away:1}},
    {fixture:{id:2908,date:'2026-09-13T16:07:00-06:00',status:{short:'FT'},venue:{name:'Estadio Akron',city:'Guadalajara'}},league:{round:'Jornada 8'},teams:{home:{id:115,name:'Chivas',logo:''},away:{id:111,name:'Pumas UNAM',logo:''}},goals:{home:3,away:0}},
    {url:'leon-vs-atletico-san-luis.html',fixture:{id:2909,date:'2026-09-14T19:00:00-06:00',status:{short:'FT'},venue:{name:'Estadio León',city:'León, Guanajuato'}},league:{round:'Jornada 8'},teams:{home:{id:100,name:'León',logo:''},away:{id:101,name:'Atlético de San Luis',logo:''}},goals:{home:2,away:0}},
    {url:'puebla-vs-atlante.html',fixture:{id:3003,date:'2026-09-18T20:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Cuauhtémoc',city:'Puebla, Puebla'}},league:{round:'Jornada 9'},teams:{home:{id:104,name:'Puebla',logo:''},away:{id:105,name:'Atlante',logo:''}},goals:{home:null,away:null}},
    {url:'juarez-vs-tigres.html',fixture:{id:3004,date:'2026-09-18T21:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Olímpico Benito Juárez',city:'Ciudad Juárez, Chihuahua'}},league:{round:'Jornada 9'},teams:{home:{id:106,name:'FC Juárez',logo:''},away:{id:107,name:'Tigres UANL',logo:''}},goals:{home:null,away:null}},
    {url:'atletico-san-luis-vs-necaxa.html',fixture:{id:3005,date:'2026-09-19T19:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Alfonso Lastras',city:'San Luis Potosí'}},league:{round:'Jornada 9'},teams:{home:{id:108,name:'Atlético de San Luis',logo:''},away:{id:109,name:'Necaxa',logo:''}},goals:{home:null,away:null}},
    {url:'atlas-vs-pumas.html',fixture:{id:3006,date:'2026-09-19T19:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Jalisco',city:'Guadalajara, Jalisco'}},league:{round:'Jornada 9'},teams:{home:{id:110,name:'Atlas',logo:''},away:{id:111,name:'Pumas UNAM',logo:''}},goals:{home:null,away:null}},
    {url:'monterrey-vs-cruz-azul.html',fixture:{id:3007,date:'2026-09-19T19:10:00-06:00',status:{short:'NS'},venue:{name:'Estadio BBVA',city:'Guadalupe, Nuevo León'}},league:{round:'Jornada 9'},teams:{home:{id:112,name:'Monterrey',logo:''},away:{id:113,name:'Cruz Azul',logo:''}},goals:{home:null,away:null}},
    {url:'america-vs-chivas.html',fixture:{id:3008,date:'2026-09-19T21:15:00-06:00',status:{short:'NS'},venue:{name:'Sede por confirmar',city:'México'}},league:{round:'Jornada 9 · Clásico Nacional'},teams:{home:{id:114,name:'América',logo:''},away:{id:115,name:'Chivas',logo:''}},goals:{home:null,away:null}},
    {url:'toluca-vs-santos.html',fixture:{id:3009,date:'2026-09-20T18:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Nemesio Díez',city:'Toluca, Estado de México'}},league:{round:'Jornada 9'},teams:{home:{id:116,name:'Toluca',logo:''},away:{id:117,name:'Santos Laguna',logo:''}},goals:{home:null,away:null}},
    {url:'pachuca-vs-tijuana.html',fixture:{id:3010,date:'2026-09-20T17:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Hidalgo',city:'Pachuca, Hidalgo'}},league:{round:'Jornada 9'},teams:{home:{id:118,name:'Pachuca',logo:''},away:{id:119,name:'Tijuana',logo:''}},goals:{home:null,away:null}},
    {url:'queretaro-vs-leon.html',fixture:{id:3011,date:'2026-09-20T17:00:00-06:00',status:{short:'NS'},venue:{name:'Estadio Corregidora',city:'Querétaro, Querétaro'}},league:{round:'Jornada 9'},teams:{home:{id:120,name:'Querétaro',logo:''},away:{id:121,name:'León',logo:''}},goals:{home:null,away:null}}
  ],
  teams: [
    {team:{id:1,name:'América',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:2,name:'Tijuana',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:3,name:'Monterrey',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:4,name:'Atlas',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:5,name:'Toluca',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:6,name:'Pumas UNAM',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:7,name:'Querétaro',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:8,name:'Guadalajara Chivas',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:9,name:'Cruz Azul',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:10,name:'Necaxa',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:11,name:'Atlante FC',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:12,name:'Puebla',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:13,name:'Pachuca',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:14,name:'León',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:15,name:'Atlético San Luis',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:16,name:'Tigres UANL',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:17,name:'Santos Laguna',logo:''},venue:{name:'Liga MX · Apertura 2026'}},
    {team:{id:18,name:'FC Juárez',logo:''},venue:{name:'Liga MX · Apertura 2026'}}
  ]
};
